server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $backend "https://security-1.codewithpeter.com";
        proxy_pass $backend$request_uri;
        proxy_ssl_server_name on;
        proxy_set_header Host security-1.codewithpeter.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
